name: xample
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1+5

environment:
  sdk: ">=2.16.1 <3.0.0" #Dart SDK 2022-02-18
  flutter: ">=2.10.2"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  extensions_package:
    git:
      url: https://github.com/RAE-Health/extensions_package.git
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_modular: ^4.4.0
  rae_asset_package:
    git:
      url: https://github.com/RAE-Health/rae_asset_package.git
  rae_widgets:
    git:
      url: https://github.com/RAE-Health/rae_widgets.git

dependency_overrides:
  theme_management:
    path: ../

dev_dependencies:
  test:
  build_runner:

flutter:
  uses-material-design: true
  generate: true
