name: theme_management
version: 0.5.0+4
homepage: http://www.raehealth.com
publish_to: 'none'

environment:
  sdk: ">=2.16.1 <3.0.0" #Dart SDK 2022-02-18
  flutter: ">=2.10.2"

dependencies:
  cupertino_icons: ^1.0.4
  extensions_package:
    git:
      url: https://github.com/RAE-Health/extensions_package.git
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_modular: ^4.4.0
  font_awesome_flutter: ^9.2.0
  hive_flutter: ^1.1.0

dependency_overrides: null

dev_dependencies:
  flutter_lints: ^1.0.4
  build_runner:
  test:

flutter:
  uses-material-design: true
  generate: false
  #switched to 'false' because of "Bad state:Bad state: Unable to generate package graph, no `.dart_tool/flutter_gen/pubspec.yaml` found"
