name: theme_management
version: 0.3.3+1
homepage: http://www.raehealth.com
publish_to: 'none'

environment:
  sdk: ">=2.15.1 <3.0.0" #Dart SDK 2021-12-20
  flutter: ">=2.8.1"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_modular: ^4.3.0
  hive_flutter: ^1.1.0
  i69n: ^2.1.0
  intl: ^0.17.0
  extensions_package:
    git:
      url: https://github.com/RAE-Health/extensions_package.git
  font_awesome_flutter: ^9.2.0

dependency_overrides: null

dev_dependencies:
  test:
  build_runner:
  localize_enum:
    git:
      url: https://github.com/RAE-Health/localize_enum.git
      path: packages/localize_enum

flutter:
  uses-material-design: true
  generate: false
  #switched to 'false' because of "Bad state:Bad state: Unable to generate package graph, no `.dart_tool/flutter_gen/pubspec.yaml` found"
